### ISSUE TITLE
Template with SELECT *

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/e-Link#64]
When creating a template where the query uses a `SELECT` instead of `CONSTRUCT` (as done in the example), the result of the template is not as expected.

Consider the following example.
```
SELECT * WHERE {
<@@@entity_uri@@@> rdfs:comment ?comment.
}
```
The result will only provide you with the comments, and the to which entities it belongs is not given. Though, we are asking for everything, using `SELECT *`.

By using a `CONSTRUCT` the issue is solved. However, I don't think the current behavior of the `SELECT *` is the expected behavior.

**Comment by m1ci** [comment]
yes, e-Link is using templates which are defined as CONSTRUCT queries. So, CONSTRUCT queries are supported at the moment only.

**Comment by pheyvaer** [comment]
Will this change in the future?
Can you add it to the documentation that a `CONSTRUCT` is required?

**Comment by m1ci** [comment]
I would rather stay with CONSTRUCT since it returns triples which can be easily added to any RDF model. For example, if the SELECT returns one resource, then it is not possible to an RDF model. 
In your, example you want to enrich an entity with a comment information. The SELECT will return just the comment text. How should we then attach this to the document? we have no info how to do this. On the other hand, CONSTRUCT enforces the clients to include this info so we can very easily add this to the model.

> Can you add it to the documentation that a CONSTRUCT is required?

@jnehring can you?

**Comment by jnehring** [comment]
Actually the documentation of POST /e-link/templates says you have to submit a CONSTRUCT query. I created an issue to add one more sentence to make it clearer:

https://github.com/freme-project/Documentation/issues/143
