### ISSUE TITLE
Exception with e-link

### ISSUE THREAD

**Issue by fsasaki** [freme-project/e-Link#65]
With the attached NIF (generated via e-entity) and the attached request I get this error message.

{
  "exception": "eu.freme.broker.exception.InvalidNIFException",
  "path": "/e-link/documents/",
  "message": "[line: 1, col: 1 ] Out of place: [KEYWORD:informat]",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1448565826671
}

What is the issue here?
[input-to-elink.txt](https://github.com/freme-project/e-Link/files/45218/input-to-elink.txt)
[e-link-request.txt](https://github.com/freme-project/e-Link/files/45219/e-link-request.txt)

**Comment by m1ci** [comment]
sorry for the delayed reply, I've just investigated the problem:

1) the ```eu.freme.broker.exception.InvalidNIFException``` was due to invalid curl request. By sending
```
curl -X POST -d@input-to-elink.ttl "http://api.freme-project.eu/0.4/e-link/documents/?informat=turtle&outformat=turtle&templateid=1" 
```
curl will set the content type header to application/x-www-form-urlencoded and thus the query parameters will be considered as part of the body. The correct request should also set the `Content-Type` header to `text/turtle`

2) I also found out that due to a rate-limiting applied to the SPARQL endpoint another exception occurred. The NIF document contains 73 entities so 73 request have been executed subsequently which leads to many requests per second. This has been solved by setting waiting time between the requests.

You can try to process the document by submitting following request:
```
curl -X POST -d @input-to-elink.txt "http://api-dev.freme-project.eu/current/e-link/documents?informat=turtle&outformat=turtle&templateid=1" -H "Content-Type: text/turtle" -v
```

**Comment by m1ci** [comment]
no active discussion, closing the issue
